@hostname = localhost:9000

###
POST http://{{hostname}}/sales-person
Content-Type: application/json

{
    "firstName": "Pedro",
    "lastName": "Pereira",
    "numberId": 68859878591
}


###
POST http://{{hostname}}/customer
Content-Type: application/json

{
    "firstName": " Fábio Gustavo",
    "lastName": "da Mata",
    "numberId": 24444991151,
    "email": "fabio_damata@midiasim.com.br",
    "phone": "(63)98381-9121",
    "address": "Avenida Filadélfia, 295",
    "city": "Setor Oeste",
    "state": "TO",
    "postal": "77816-540"
}

###
POST http://{{hostname}}/vendor
Content-Type: application/json

{
    "companyName": "TechLog Atacado Integrado",
    "brandName": "TechLog",
    "ein": "131213141",
    "phone": "(18)2980-8723",
    "address": "Rua Ricardo Anderson Cristófano, 447",
    "city": "Paraíso",
    "state": "SP",
    "postal": "04104-090"
}

###
POST http://{{hostname}}/product
Content-Type: application/json

{
    "name": "produto 1",
    "description": "produto 1",
    "price": 90,
    "vendorId": 1,
    "productCategoryId": 1
}

###
POST http://{{hostname}}/product-category
Content-Type: application/json

{
    "name": "category 1",
    "description": "description 1"
}

###
POST http://{{hostname}}/order
Content-Type: application/json

{
    "customerId": 1,
    "salesPersonId": 3,
    "orderInfos": [
      {
        "productId": 2,
        "quantity": 2
      },
      {
        "productId": 3,
        "quantity": 1
      }
    ]
}


###
GET http://{{hostname}}/order/4
Content-Type: application/json
